# Generated by Django 5.2.10 on 2026-02-03 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farm', '0031_alter_order_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.hub')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.orderitem')),
            ],
            options={
                'verbose_name': 'issue record',
                'verbose_name_plural': 'issue records',
                'ordering': ('-issued_at',),
                'indexes': [models.Index(fields=['issued_at', 'issued_by'], name='logistics_i_issued__30f8fd_idx')],
                'constraints': [models.UniqueConstraint(fields=('order_item', 'hub'), name='unique_issue_event')],
            },
        ),
        migrations.CreateModel(
            name='TransferRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sent', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity_received', models.DecimalField(decimal_places=2, max_digits=8)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_transit', 'In transit'), ('received', 'Received'), ('rejected', 'Rejected')], default='in_transit', max_length=20)),
                ('from_farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.farm')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.orderitem')),
                ('to_hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.hub')),
            ],
            options={
                'verbose_name': 'transfer record',
                'verbose_name_plural': 'transfer records',
                'ordering': ('-received_at',),
                'indexes': [models.Index(fields=['received_at'], name='logistics_t_receive_d01e24_idx')],
            },
        ),
    ]
