# Generated by Django 5.2.10 on 2026-02-16 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farm', '0001_initial'),
        ('transit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='County names. e.g Nairobi', max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='TransportAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('loading', 'Loading'), ('in_transit', 'In Transit'), ('arrived', 'Arrived'), ('closed', 'Closed')], default='loading', max_length=20)),
                ('departed_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='transit.transportbooking')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transit.carrier')),
                ('from_hub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatches', to='farm.hub')),
                ('to_hub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='farm.hub')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transit.vehiclecategory')),
            ],
            options={
                'verbose_name': 'Transport Assignment',
                'verbose_name_plural': 'Transport Assignments',
                'ordering': ('-departed_at',),
            },
        ),
        migrations.CreateModel(
            name='IssueRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.hub')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.orderitem')),
            ],
            options={
                'verbose_name': 'issue record',
                'verbose_name_plural': 'issue records',
                'ordering': ('-issued_at',),
                'indexes': [models.Index(fields=['issued_at', 'issued_by'], name='logistics_i_issued__30f8fd_idx')],
                'constraints': [models.UniqueConstraint(fields=('order_item', 'hub'), name='unique_issue_event')],
            },
        ),
        migrations.CreateModel(
            name='TransferRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sent', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity_received', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('Preparing', 'Preparing'), ('PARTIALLY_DISPATCHED', 'Partially Dispatched'), ('IN_TRANSIT', 'In Transit'), ('Ready', 'Ready'), ('Dispatched', 'Dispatched'), ('Completed', 'Completed'), ('RECEIVED', 'Received')], default='IN_TRANSIT', max_length=20)),
                ('from_hub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfers', to='farm.hub')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.orderitem')),
                ('to_hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='farm.hub')),
            ],
            options={
                'verbose_name': 'transfer record',
                'verbose_name_plural': 'transfer records',
                'ordering': ('-sent_at',),
                'indexes': [models.Index(fields=['sent_at'], name='logistics_t_sent_at_36461f_idx')],
            },
        ),
    ]
