# Generated by Django 5.2.10 on 2026-02-16 15:50

from django.db import migrations


COUNTIES = [
    "Nairobi", "Kiambu", "Nakuru", "Uasin Gishu", "Kericho",
    "Bungoma", "Kakamega", "Kisumu", "Siaya", "Homa Bay",
    "Migori", "Kisii", "Nyamira", "Narok", "Kajiado",
    "Machakos", "Makueni", "Kitui", "Embu", "Meru",
    "Tharaka Nithi", "Laikipia", "Nyeri", "Murang'a", "Kirinyaga",
    "Nyandarua", "Nandi", "Bomet", "Elgeyo Marakwet",
    "Trans Nzoia", "West Pokot", "Samburu", "Baringo",
    "Turkana", "Marsabit", "Isiolo", "Garissa",
    "Wajir", "Mandera", "Tana River",
    "Lamu", "Taita Taveta", "Mombasa",
    "Kilifi", "Kwale", "Vihiga"
]

def create_locations(apps, schema_editor):
    Location = apps.get_model("logistics", "Location")
    for name in COUNTIES:
        Location.objects.get_or_create(name=name)

class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_locations),
    ]