# Generated by Django 5.2.10 on 2026-02-04 08:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0032_orderitem_status'),
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferrecord',
            name='from_farm',
        ),
        migrations.AddField(
            model_name='transferrecord',
            name='from_hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfers', to='farm.hub'),
        ),
        migrations.AddField(
            model_name='transferrecord',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transferrecord',
            name='status',
            field=models.CharField(choices=[('in_transit', 'In transit'), ('received', 'Received'), ('rejected', 'Rejected'), ('damaged', 'Damaged')], default='in_transit', max_length=20),
        ),
        migrations.AlterField(
            model_name='transferrecord',
            name='to_hub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='farm.hub'),
        ),
    ]
