# Generated by Django 5.2.10 on 2026-02-17 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_auto_20260216_1850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ('name',), 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
    ]
