# Generated by Django 5.2.10 on 2026-02-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0032_orderitem_status'),
        ('logistics', '0002_remove_transferrecord_from_farm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Molo Market', max_length=255, unique=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ('-pk',),
            },
        ),
        migrations.AlterModelOptions(
            name='transferrecord',
            options={'ordering': ('-sent_at',), 'verbose_name': 'transfer record', 'verbose_name_plural': 'transfer records'},
        ),
        migrations.RemoveIndex(
            model_name='transferrecord',
            name='logistics_t_receive_d01e24_idx',
        ),
        migrations.AddIndex(
            model_name='transferrecord',
            index=models.Index(fields=['sent_at'], name='logistics_t_sent_at_36461f_idx'),
        ),
        migrations.AddField(
            model_name='location',
            name='hub',
            field=models.ManyToManyField(related_name='my_location', to='farm.hub'),
        ),
    ]
