# Generated by Django 5.2.10 on 2026-02-05 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_location_alter_transferrecord_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(help_text='County names. e.g Nairobi', max_length=255, unique=True),
        ),
    ]
