# Generated by Django 5.2.10 on 2026-02-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_alter_location_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferrecord',
            name='quantity_received',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
