# Generated by Django 5.2.10 on 2026-02-06 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_alter_transferrecord_quantity_received'),
        ('transit', '0009_delete_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('loading', 'Loading'), ('in_transit', 'In Transit'), ('arrived', 'Arrived'), ('closed', 'Closed')], default='loading', max_length=20)),
                ('departed_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='transit.transportbooking')),
            ],
            options={
                'verbose_name': 'Transport Assignment',
                'verbose_name_plural': 'Transport Assignments',
                'ordering': ('-departed_at',),
            },
        ),
    ]
