# Generated by Django 5.2.10 on 2026-02-06 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0033_alter_farm_owner'),
        ('logistics', '0006_transportassignment'),
        ('transit', '0010_carrier_alter_transportbooking_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportassignment',
            name='carrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transit.carrier'),
        ),
        migrations.AddField(
            model_name='transportassignment',
            name='from_hub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatches', to='farm.hub'),
        ),
        migrations.AddField(
            model_name='transportassignment',
            name='to_hub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='farm.hub'),
        ),
        migrations.AddField(
            model_name='transportassignment',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transit.vehiclecategory'),
        ),
    ]
