# Generated by Django 5.2.10 on 2026-02-07 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_transportassignment_carrier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='hub',
        ),
        migrations.RemoveField(
            model_name='location',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='longitude',
        ),
    ]
