# Generated by Django 5.2.10 on 2026-02-17 13:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_initial'),
        ('logistics', '0003_alter_location_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='area_machines', to='logistics.location'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'active_role': 'equipment_owner'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quantity per unit, e.g., 50 for a 50kg bag', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
