# Generated by Django 5.2.10 on 2026-02-17 19:59

import django.core.validators
import farm.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_alter_equipment_location_alter_equipment_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequentquestion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='image',
            field=models.ImageField(upload_to='equipment_img', validators=[farm.utils.validators.validate_image_size, farm.utils.validators.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
