# Generated by Django 4.2.7 on 2023-11-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0006_alter_equipment_name_alter_equipment_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='slug',
            field=models.SlugField(),
        ),
    ]
