# Generated by Django 4.2.7 on 2023-12-09 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0010_alter_review_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('subject', models.CharField(max_length=100)),
                ('admin_responded', models.BooleanField(default=False)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.equipment')),
            ],
            options={
                'verbose_name': 'Equipment Inquiry',
                'verbose_name_plural': 'Equipments Inquiry',
                'ordering': ('-pk',),
            },
        ),
    ]
