# Generated by Django 4.2.7 on 2026-01-10 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farm', '0011_equipmentinquiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unit_of_measurement',
        ),
        migrations.AddField(
            model_name='product',
            name='unit_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quantity per unit, e.g., 50 for a 50kg bag', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_quantity_type',
            field=models.CharField(blank=True, choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('ton', 'Tonne'), ('l', 'Liter'), ('ml', 'Milliliter'), ('pcs', 'Pieces'), ('bag', 'Bag'), ('crate', 'Crate'), ('bundle', 'Bundle'), ('dozen', 'Dozen'), ('box', 'Box')], help_text='Unit type of the quantity', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'role': 'farmer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
