# Generated by Django 4.2.7 on 2026-01-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0013_equipmentreview_platformreview_productreview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentinquiry',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipmentinquiry',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
