# Generated by Django 5.2.10 on 2026-01-15 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_buyerprofile_options_and_more'),
        ('farm', '0015_equipmentrental'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentinquiry',
            options={'ordering': ('-created_at',), 'verbose_name': 'Equipment Inquiry', 'verbose_name_plural': 'Equipment Inquiries'},
        ),
        migrations.AlterModelOptions(
            name='equipmentrental',
            options={'ordering': ('created_at',), 'verbose_name': 'Equipment Rental', 'verbose_name_plural': 'Equipment Rentals'},
        ),
        migrations.RenameField(
            model_name='equipmentinquiry',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='equipmentinquiry',
            name='admin_responded',
        ),
        migrations.RemoveField(
            model_name='equipmentinquiry',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='equipmentinquiry',
            name='email',
        ),
        migrations.RemoveField(
            model_name='equipmentinquiry',
            name='subject',
        ),
        migrations.AddField(
            model_name='equipmentinquiry',
            name='requested_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipmentinquiry',
            name='requested_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipmentinquiry',
            name='requester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_inquiries', to='accounts.buyerprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipmentinquiry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('responded', 'Responded'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='equipmentinquiry',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='farm.equipment'),
        ),
    ]
