# Generated by Django 5.2.10 on 2026-01-19 17:40

import farm.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0017_alter_equipmentinquiry_requester'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_perishable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='equipmentinquiry',
            name='requested_end_date',
            field=models.DateField(blank=True, null=True, validators=[farm.validators.validate_date_is_not_past]),
        ),
        migrations.AlterField(
            model_name='equipmentinquiry',
            name='requested_start_date',
            field=models.DateField(blank=True, null=True, validators=[farm.validators.validate_date_is_not_past]),
        ),
    ]
