# Generated by Django 5.2.10 on 2026-01-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0022_remove_order_products_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
