# Generated by Django 5.2.10 on 2026-01-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0023_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('wallet', 'Wallet'), ('mpesa', 'M-Pesa'), ('card', 'Card'), ('cash', 'Cash on Delivery')], max_length=20),
        ),
    ]
