# Generated by Django 5.2.10 on 2026-01-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0024_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('wallet', 'Wallet'), ('mpesa', 'M-Pesa'), ('card', 'Card'), ('pay_on_delivery', 'Pay on Delivery')], max_length=20),
        ),
    ]
