# Generated by Django 5.2.10 on 2026-01-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0026_remove_order_transaction_id_order_order_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_reference',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
