# Generated by Django 5.2.10 on 2026-01-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0028_alter_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_checkout_active',
            field=models.BooleanField(default=True),
        ),
    ]
