# Generated by Django 5.2.10 on 2026-02-01 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0029_order_is_checkout_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-order_date',), 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ('-pk',), 'verbose_name': 'Order Item', 'verbose_name_plural': 'Order Items'},
        ),
    ]
