# Generated by Django 5.2.10 on 2026-02-04 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0031_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('Preparing', 'Preparing'), ('Ready', 'Ready'), ('Dispatched', 'Dispatched'), ('Completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
