# Generated by Django 5.2.10 on 2026-02-07 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0033_alter_farm_owner'),
        ('logistics', '0008_remove_location_hub_remove_location_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hub',
            name='county',
        ),
        migrations.AddField(
            model_name='hub',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hubs', to='logistics.location'),
        ),
    ]
