# Generated by Django 5.2.10 on 2026-02-08 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0034_remove_hub_county_hub_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='unit_quantity',
            new_name='unit_weight_kg',
        ),
    ]
