# Generated by Django 5.2.10 on 2026-02-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0035_rename_unit_quantity_product_unit_weight_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('Preparing', 'Preparing'), ('PARTIALLY_DISPATCHED', 'Partially Dispatched'), ('IN_TRANSIT', 'In Transit'), ('Ready', 'Ready'), ('Dispatched', 'Dispatched'), ('Completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
