# Generated by Django 5.2.10 on 2026-02-15 13:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0036_alter_orderitem_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreview',
            options={'ordering': ('-review_date',), 'verbose_name': 'Product Review', 'verbose_name_plural': 'Product Reviews'},
        ),
        migrations.RenameField(
            model_name='equipmentreview',
            old_name='review',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='platformreview',
            old_name='review',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='productreview',
            old_name='review',
            new_name='comment',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('Preparing', 'Preparing'), ('PARTIALLY_DISPATCHED', 'Partially Dispatched'), ('IN_TRANSIT', 'In Transit'), ('Ready', 'Ready'), ('Dispatched', 'Dispatched'), ('Completed', 'Completed'), ('RECEIVED', 'Received')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['product'], name='farm_produc_product_48362f_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['customer'], name='farm_produc_custome_2fd9e9_idx'),
        ),
    ]
