# Generated by Django 5.2.10 on 2026-02-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerprofile',
            name='notification',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='equipmentownerprofile',
            name='notification',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='notification',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='notification',
            field=models.BooleanField(default=True),
        ),
    ]
