# Generated by Django 5.2.10 on 2026-01-15 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='facebook_username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='image',
            field=models.ImageField(default='profile.png', upload_to='img'),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='instagram_username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='facebook_username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='image',
            field=models.ImageField(default='profile.png', upload_to='img'),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='instagram_username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='notification',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
