# Generated by Django 5.2.10 on 2026-01-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_buyerprofile_bio_buyerprofile_facebook_username_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyerprofile',
            options={'verbose_name': 'Buyer Profile', 'verbose_name_plural': 'Buyer Profiles'},
        ),
        migrations.AlterModelOptions(
            name='equipmentownerprofile',
            options={'verbose_name': 'Equipment Owner Profile', 'verbose_name_plural': 'Equipment Owner Profiles'},
        ),
        migrations.RemoveField(
            model_name='buyerprofile',
            name='payment_info',
        ),
        migrations.RemoveField(
            model_name='buyerprofile',
            name='purchase_hostory',
        ),
        migrations.RemoveField(
            model_name='equipmentownerprofile',
            name='rental_history',
        ),
        migrations.AddField(
            model_name='equipmentownerprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipmentownerprofile',
            name='facebook_username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='equipmentownerprofile',
            name='image',
            field=models.ImageField(default='profile.png', upload_to='img'),
        ),
        migrations.AddField(
            model_name='equipmentownerprofile',
            name='instagram_username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='equipmentownerprofile',
            name='notification',
            field=models.BooleanField(default=False),
        ),
    ]
