# Generated by Django 5.2.10 on 2026-02-01 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='role',
            new_name='active_role',
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='profile.png', upload_to='img')),
                ('bio', models.TextField(blank=True, null=True)),
                ('facebook_username', models.CharField(blank=True, max_length=50, null=True)),
                ('instagram_username', models.CharField(blank=True, max_length=50, null=True)),
                ('notification', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('delivery', 'Delivery'), ('warehouse', 'Warehouse'), ('admin', 'Admin')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Profile',
                'verbose_name_plural': 'Staff Profiles',
                'ordering': ('-pk',),
            },
        ),
    ]
