# Generated by Django 5.2.10 on 2026-02-05 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_role_user_active_role_staffprofile'),
        ('farm', '0033_alter_farm_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='my_hub', to='farm.hub'),
        ),
    ]
