# Generated by Django 4.2.7 on 2023-11-27 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=200, unique=True)),
                ('account_balance', models.DecimalField(decimal_places=2, default=1000000, max_digits=12)),
                ('opening_date', models.DateTimeField()),
                ('last_transaction_date', models.DateTimeField(null=True)),
                ('total_withdraw', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('total_deposit', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('total_transfar', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('total_paybil', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('total_trans_amount', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ('-pk',),
            },
        ),
    ]
