# Generated by Django 4.2.7 on 2023-11-29 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_customersession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='total_paybil',
            new_name='total_payment',
        ),
        migrations.RemoveField(
            model_name='account',
            name='total_trans_amount',
        ),
        migrations.RemoveField(
            model_name='account',
            name='total_transfar',
        ),
        migrations.RemoveField(
            model_name='account',
            name='total_withdraw',
        ),
    ]
