# Generated by Django 5.2.10 on 2026-01-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_payout_payoutitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payout',
            options={'ordering': ('-created_at',), 'verbose_name': 'Payout', 'verbose_name_plural': 'Payouts'},
        ),
        migrations.AlterModelOptions(
            name='payoutitem',
            options={'ordering': ('-pk',), 'verbose_name': 'PayoutItem', 'verbose_name_plural': 'PayoutItems'},
        ),
        migrations.AlterField(
            model_name='account',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
