# Generated by Django 4.2.7 on 2023-11-22 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farm', '0009_frequentquestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(max_length=200)),
                ('transport_option', models.CharField(choices=[('Standard Delivery', 'Standard Delivery'), ('Express Delivery', 'Express Delivery')], max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pickup_date_time', models.DateTimeField()),
                ('delivery_dateTime', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Transit', 'Transit'), ('Delivered', 'Delivered')], default='Pending', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farm.order')),
            ],
            options={
                'verbose_name': 'Transport Booking',
                'verbose_name_plural': 'Transport Bookings',
                'ordering': ('-pk',),
                'unique_together': {('customer', 'order')},
            },
        ),
    ]
