# Generated by Django 4.2.7 on 2023-11-25 06:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import transit.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farm', '0009_frequentquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(max_length=100, verbose_name='Departure')),
                ('delivery', models.CharField(max_length=100, verbose_name='Delivery')),
                ('weight', models.DecimalField(decimal_places=3, help_text='units kgs', max_digits=10, validators=[django.core.validators.MinValueValidator(limit_value=0.001, message='Weight must be at least 0.001 Kgs'), django.core.validators.MaxValueValidator(limit_value=1000000, message='Weight can not exceed 1,000,000 kgs')], verbose_name='Weight')),
                ('dimensions', models.CharField(max_length=50, validators=[transit.validators.DimensionsValidator()], verbose_name='Demensions')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Enter a valid email')], verbose_name='Email')),
                ('phone', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Phone must start with a country code (+)', regex='^\\+\\d{1,}'), django.core.validators.MinLengthValidator(limit_value=13, message='Phone number is too short')], verbose_name='Phone')),
                ('message', models.TextField(verbose_name='Message')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransportBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(max_length=200)),
                ('transport_option', models.CharField(choices=[('Standard Delivery', 'Standard Delivery'), ('Express Delivery', 'Express Delivery')], max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pickup_date_time', models.DateTimeField()),
                ('delivery_dateTime', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Transit', 'Transit'), ('Delivered', 'Delivered')], default='Pending', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farm.order')),
            ],
            options={
                'verbose_name': 'Transport Booking',
                'verbose_name_plural': 'Transport Bookings',
                'ordering': ('-pk',),
                'unique_together': {('customer', 'order')},
            },
        ),
    ]
