# Generated by Django 5.2.10 on 2026-02-16 02:03

import django.core.validators
import django.db.models.deletion
import transit.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(max_length=100, verbose_name='Departure')),
                ('delivery', models.CharField(max_length=100, verbose_name='Delivery')),
                ('weight', models.DecimalField(decimal_places=3, help_text='units kgs', max_digits=10, validators=[django.core.validators.MinValueValidator(limit_value=0.001, message='Weight must be at least 0.001 Kgs'), django.core.validators.MaxValueValidator(limit_value=1000000, message='Weight can not exceed 1,000,000 kgs')], verbose_name='Weight')),
                ('dimensions', models.CharField(max_length=50, validators=[transit.validators.DimensionsValidator()], verbose_name='Demensions')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Enter a valid email')], verbose_name='Email')),
                ('phone', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Phone must start with a country code (+)', regex='^\\+\\d{1,}'), django.core.validators.MinLengthValidator(limit_value=13, message='Phone number is too short')], verbose_name='Phone')),
                ('message', models.TextField(verbose_name='Message')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TerrainAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_type', models.CharField(choices=[('tarmac', 'Highway/Tarmac'), ('rural', 'Rural/Muruam'), ('difficult', 'Off-road/Muddy')], max_length=20, unique=True)),
                ('multiplier', models.DecimalField(decimal_places=2, default=100, max_digits=4)),
            ],
            options={
                'verbose_name': 'Terrain Adjustment',
                'verbose_name_plural': 'Terrain Adjustments',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g Pickup, 3-Ton Truck', max_length=50)),
                ('base_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_per_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_capacity_kg', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Vehicle Category',
                'verbose_name_plural': 'Vehicle Categories',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='TransportBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_option', models.CharField(choices=[('STANDARD', 'Standard Delivery'), ('EXPRESS', 'Express Delivery')], max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('requested_pickup_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIALLY_DISPATCHED', 'Partially Dispatched'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination_hub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_bookings', to='farm.hub')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transport', to='farm.order')),
                ('source_hub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_query_name='out_going_booking', to='farm.hub')),
            ],
            options={
                'verbose_name': 'Transport Booking',
                'verbose_name_plural': 'Transport Bookings',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TransportBookingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transit.transportbooking')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.orderitem')),
            ],
            options={
                'verbose_name': 'transport booking item',
                'verbose_name_plural': 'transport booking items',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=50)),
                ('rating', models.FloatField(default=5.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='my_company', to='transit.vehiclecategory')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
