# Generated by Django 4.2.7 on 2023-11-26 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0002_alter_quote_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transportbooking',
            options={'ordering': ('-pk', '-delivery_dateTime'), 'verbose_name': 'Transport Booking', 'verbose_name_plural': 'Transport Bookings'},
        ),
    ]
