# Generated by Django 5.2.10 on 2026-01-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0003_alter_transportbooking_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Molo Market', max_length=255, unique=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='TerrainAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_type', models.CharField(choices=[('tarmac', 'Highway/Tarmac'), ('rural', 'Rural/Muruam'), ('difficult', 'Off-road/Muddy')], max_length=20, unique=True)),
                ('multiplier', models.DecimalField(decimal_places=2, default=100, max_digits=4)),
            ],
            options={
                'verbose_name': 'Terrain Adjustment',
                'verbose_name_plural': 'Terrain Adjustments',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g Pickup, 3-Ton Truck', max_length=50)),
                ('base_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_per_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_capacity_kg', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Vehicle Category',
                'verbose_name_plural': 'Vehicle Categories',
                'ordering': ('-pk',),
            },
        ),
    ]
