# Generated by Django 5.2.10 on 2026-01-26 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0023_alter_order_status'),
        ('transit', '0004_location_terrainadjustment_vehiclecategory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transportbooking',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='transportbooking',
            name='destination',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transportbooking',
            name='order_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transport', to='farm.orderitem'),
        ),
        migrations.RemoveField(
            model_name='transportbooking',
            name='order',
        ),
    ]
