# Generated by Django 5.2.10 on 2026-02-01 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0031_alter_order_status_and_more'),
        ('transit', '0005_alter_transportbooking_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportbooking',
            name='order_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transport', to='farm.order'),
        ),
    ]
