# Generated by Django 5.2.10 on 2026-02-02 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0006_alter_transportbooking_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportbooking',
            name='carrier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
