# Generated by Django 5.2.10 on 2026-02-02 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0007_transportbooking_carrier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transportbooking',
            old_name='order_item',
            new_name='order',
        ),
    ]
