# Generated by Django 5.2.10 on 2026-02-04 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0008_rename_order_item_transportbooking_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
