# Generated by Django 5.2.10 on 2026-02-06 16:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0033_alter_farm_owner'),
        ('transit', '0009_delete_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=50)),
                ('rating', models.FloatField(default=5.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterModelOptions(
            name='transportbooking',
            options={'ordering': ('-created_at',), 'verbose_name': 'Transport Booking', 'verbose_name_plural': 'Transport Bookings'},
        ),
        migrations.RenameField(
            model_name='transportbooking',
            old_name='pickup_date_time',
            new_name='requested_pickup_at',
        ),
        migrations.RemoveField(
            model_name='transportbooking',
            name='carrier',
        ),
        migrations.RemoveField(
            model_name='transportbooking',
            name='delivery_dateTime',
        ),
        migrations.RemoveField(
            model_name='transportbooking',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='transportbooking',
            name='pickup_location',
        ),
        migrations.RemoveField(
            model_name='transportbooking',
            name='status',
        ),
        migrations.AddField(
            model_name='transportbooking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportbooking',
            name='destination_hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_bookings', to='farm.hub'),
        ),
    ]
