# Generated by Django 5.2.10 on 2026-02-06 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0033_alter_farm_owner'),
        ('transit', '0010_carrier_alter_transportbooking_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportbooking',
            name='source_hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_bookings', to='farm.hub'),
        ),
        migrations.AlterField(
            model_name='transportbooking',
            name='transport_option',
            field=models.CharField(choices=[('STANDARD', 'Standard Delivery'), ('EXPRESS', 'Express Delivery')], max_length=100),
        ),
    ]
