# Generated by Django 5.2.10 on 2026-02-06 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0011_transportbooking_source_hub_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportbooking',
            name='source_hub',
        ),
    ]
