# Generated by Django 5.2.10 on 2026-02-07 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0033_alter_farm_owner'),
        ('transit', '0012_remove_transportbooking_source_hub'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportbooking',
            name='source_hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_query_name='out_going_booking', to='farm.hub'),
        ),
        migrations.AddField(
            model_name='transportbooking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Transit', 'Transit'), ('Delivered', 'Delivered')], default='Pending', max_length=20),
        ),
        migrations.CreateModel(
            name='TransportBookingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transit.transportbooking')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.orderitem')),
            ],
            options={
                'verbose_name': 'transport booking item',
                'verbose_name_plural': 'transport booking items',
                'ordering': ('-created_at',),
            },
        ),
    ]
