# Generated by Django 5.2.10 on 2026-02-07 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0013_transportbooking_source_hub_transportbooking_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportbooking',
            name='customer',
        ),
    ]
