# Generated by Django 5.2.10 on 2026-02-07 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0034_remove_hub_county_hub_location'),
        ('transit', '0014_remove_transportbooking_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportbooking',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transport', to='farm.order'),
        ),
    ]
