# Generated by Django 5.2.10 on 2026-02-08 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0015_alter_transportbooking_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='my_company', to='transit.vehiclecategory'),
            preserve_default=False,
        ),
    ]
