# Generated by Django 5.2.10 on 2026-02-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0016_carrier_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportbooking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PARTIALLY_DISPATCHED', 'Partially Dispatched'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=20),
        ),
    ]
