name: Django CI

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        cd harvestsaver
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        cd harvestsaver
        export SECRET_KEY="$SECRET_KEY"
        echo "SECRECT_KEY: $SECRET_KEY "
        python manage.py test

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Development Server
      run: |
        cd harvestsaver

        scp -r . ubuntu:54.146.57.34:/live

        ssh ubuntu@54.146.57.34 << 'EOF'
        cd live

        python manage.py migrate

        systemctl restart gunicorn
        systemctl restart nginx
    EOF 