name: Deveopment workflow (Development)

on:
  push:
    branches: ["development" ]
  pull_request:
    branches: ["development" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      MY_ENVIRONMENT: development
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        cd harvestsaver
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        cd harvestsaver
        export SECRET_KEY="$SECRET_KEY"
        echo "SECRECT_KEY: $SECRET_KEY "
        python manage.py test

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Decrypt .env file
      run: |
        cd harvestsaver
        echo "Decryption Key: ${{ secrets.DECRYPTION_KEY }}"
        openssl aes-256-cbc -d -a -in harvestsaver/.env.enc -out harvestsaver/.env -k "${{ secrets.DECRYPTION_KEY }}" -pbkdf2

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

    - name: Adding know Hosts
      run: ssh-keyscan -H 18.210.13.40 >> ~/.ssh/known_hosts

    - name: Copying files
      run: rsync -avz . ubuntu@18.210.13.40:~/live/harvestsaver

    - name: SSH into the Server and Deploy
      run: |
        ssh ubuntu@18.210.13.40 "cd ~/live/harvestsaver/harvestsaver && \
        source ~/live/harvestsaver/venv/bin/activate && \
        pip install -r requirements.txt && \
        python manage.py migrate && \
        python manage.py collectstatic --noinput && \
        sudo systemctl restart gunicorn && \
        sudo systemctl restart nginx"
